change run_tests file

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -1,7 +1,7 @@
 # Note that this script is taken from raven "raven/run_tests". Some changes were made to make
 #!/bin/bash
 echo 'Running FORCE tests ...'
-PYTHON_COMMAND=python
+
 SCRIPT_NAME=`readlink $0`
 if test -x "$SCRIPT_NAME";
 then
@@ -14,7 +14,7 @@ SCRIPT_DIR=`(cd $SCRIPT_DIRNAME; pwd)`
 TEST_SET=0 # 0 for normal tests, 1 for plugin tests, 2 for both
 
 # source read ravenrc script
-RAVEN_RC_SCRIPT=$SCRIPT_DIR/scripts/read_ravenrc.sh
+RAVEN_RC_SCRIPT=$SCRIPT_DIR/raven/scripts/read_ravenrc.sh
 RAVEN_RC_SCRIPT="${RAVEN_RC_SCRIPT//\\//}"
 source $RAVEN_RC_SCRIPT
 
@@ -42,7 +42,7 @@ done
 echo 'Loading libraries ...'
 if  [[ "$INSTALLATION_MANAGER" == "CONDA" ]];
 then
-    source $SCRIPT_DIR/scripts/establish_conda_env.sh --load
+    source $SCRIPT_DIR/raven/scripts/establish_conda_env.sh --load
 elif [[ "$INSTALLATION_MANAGER" == "PIP" ]];
 then
     source $SCRIPT_DIR/scripts/establish_conda_env.sh --load --installation-manager PIP
@@ -80,6 +80,9 @@ for A in "$@"; do
     esac
 done
 
+#Note that this is from the perspective of python, otherwise would be
+# identical to $SCRIPT_DIR (which matters on windows, but not elsewhere)
+RAVEN_DIR=`$PYTHON_COMMAND $SCRIPT_DIR/raven/scripts/plugin_handler.py -r`
 
 
 
@@ -100,7 +103,9 @@ if [[ $DO_RAVEN == 0 ]]; then
   echo
   echo 'Running FORCE tests ...'
 
-  $PYTHON_COMMAND $SCRIPT_DIR/rook/main.py --config-file=$SCRIPT_DIR/developer_tools/rook.ini "${ARGS[@]}"
+  $PYTHON_COMMAND $SCRIPT_DIR/raven/rook/main.py --config-file=$SCRIPT_DIR/developer_tools/rook.ini --testers-dir $RAVEN_DIR/scripts/TestHarness/testers,$RAVEN_DIR/../HERON/src/Testers "${ARGS[@]}"
+  #   ROOK_COMMAND="$PYTHON_COMMAND $SCRIPT_DIR/rook/main.py --test-dir $LOCATION --testers-dir $RAVEN_DIR/scripts/TestHarness/testers,$LOCATION/../src/Testers --add-non-default-run-types qsub ${ARGS[@]}"
+
   # store return codes individually (rc) and combined (ALL_PASS)
   rc=$?
   ALL_PASS=$rc
@@ -112,26 +117,61 @@ if [[ $DO_RAVEN == 0 ]]; then
       PASSED=( "${PASSED[@]}" "RAVEN" )
   fi # end "if passed"
 
+
 fi   # end "if do raven"
 
-## FINISHED running tests
+# # now do plugins
 
-# report results
-echo
-echo "********************************************************************************"
-echo
-if [[ $ALL_PASS != 0 ]]; then
-  # if no tests were run, this should not be possible!
-  echo  ... there were failed tests!
-  echo The following test sets passed: ${PASSED[@]}
-  echo The following test sets failed: ${FAILED[@]}
-  exit $ALL_PASS
-else
-  # check if NO tests were run
-  if [ ${#PASSED[@]} -eq 0 ]; then
-    echo WARNING: no test sets were checked!
-  else
-    echo Tested sets: ${PASSED[@]}
-  fi
-  echo ... tests passed!
-fi
+# # Now run the plugin tests
+# echo 'Loading plugin tests ...'
+# PLUGINS=$($PYTHON_COMMAND $SCRIPT_DIR/raven/scripts/plugin_handler.py -l)
+# for P in $PLUGINS; do
+#   LOCATION=$($PYTHON_COMMAND $SCRIPT_DIR/raven/scripts/plugin_handler.py -f $P)/tests
+#   # TODO extend config to use RAVEN and PLUGIN config options without redoing all tests
+#   echo
+#   echo "********************************************************************************"
+#   echo
+#   echo Starting tests for plugin "$P" ...
+#   # add RAVEN testers to plugin testers
+#   ROOK_COMMAND="$PYTHON_COMMAND $SCRIPT_DIR/rook/main.py --test-dir $LOCATION --testers-dir $RAVEN_DIR/scripts/TestHarness/testers,$LOCATION/../src/Testers --add-non-default-run-types qsub ${ARGS[@]}"
+#   echo Running ROOK command: "$ROOK_COMMAND" ...
+#   {
+#     # try
+#     $ROOK_COMMAND
+#     rc=$?
+#   } || {
+#     # catch
+#     rc=1
+#   }
+
+#   ALL_PASS=$(($ALL_PASS + $rc))
+#   if [[ $rc != 0 ]]; then
+#     echo  ... there were failed tests for plugin "$P"!
+#     FAILED=( "${FAILED[@]}" "$P" )
+#   else
+#     echo Tests passed for plugin "$P".
+#     PASSED=( "${PASSED[@]}" "$P" )
+#   fi
+# done  # finish "for each plugin"
+
+# # ## FINISHED running tests
+
+# # report results
+# echo
+# echo "********************************************************************************"
+# echo
+# if [[ $ALL_PASS != 0 ]]; then
+#   # if no tests were run, this should not be possible!
+#   echo  ... there were failed tests!
+#   echo The following test sets passed: ${PASSED[@]}
+#   echo The following test sets failed: ${FAILED[@]}
+#   exit $ALL_PASS
+# else
+#   # check if NO tests were run
+#   if [ ${#PASSED[@]} -eq 0 ]; then
+#     echo WARNING: no test sets were checked!
+#   else
+#     echo Tested sets: ${PASSED[@]}
+#   fi
+#   echo ... tests passed!
+# fi
